from enum import Enum
import json
from pathlib import Path
import tomllib

from ninja_syntax import Writer

SCRIPTS_DIR = Path(__file__).parent


class BuildType(Enum):
    NORMAL = 1
    BUGFIX = 2
    DIFFBUILD = 3
    DLLBUILD = 4
    OBJDIFFBUILD = 5


def configure(build_type):
    with (SCRIPTS_DIR.parent / "build.ninja").open("w") as f:
        writer = Writer(f, width=120)
        writer.variable("ninja_required_version", "1.5")

        writer.variable("builddir", "build")

        writer.variable("cl", "cl.exe")
        writer.variable(
            "cl_common_flags",
            '/MT /EHsc /Gs /DNDEBUG /Zi /Fp"build\\th_pch.pch" /Fd"build\\vc70.pdb" /Gy /GF /I $builddir/autogenerated /I src /I 3rdparty/Detours/src',
        )

        writer.variable("cl_flags", "$cl_common_flags /Oi /Gr")
        writer.variable("cl_flags_pbg", "$cl_common_flags /Od /Oi /Ob0 /Gr")

        if build_type == BuildType.BUGFIX:
            writer.variable("cl_flags", "$cl_flags /DFIX_REALLY_BAD_BUGS")
            writer.variable("cl_flags_pbg", "$cl_flags_pbg /DFIX_REALLY_BAD_BUGS")
        writer.variable(
            "cl_flags_detours",
            "/W4 /WX /we4777 /we4800 /Zi /MT /Gy /Gm- /Zl /Od /DDETOUR_DEBUG=0 /DWIN32_LEAN_AND_MEAN /D_WIN32_WINNT=0x501",
        )
        if build_type in [BuildType.DIFFBUILD, BuildType.DLLBUILD]:
            writer.variable("cl_flags", "$cl_flags /DDIFFBUILD")
            writer.variable("cl_flags_pbg", "$cl_flags_pbg /DDIFFBUILD")
        writer.variable("rc", "rc.exe")
        writer.variable("link", "link.exe")
        writer.variable(
            "th08_link_flags",
            # Whole-image evidence requires target-retained unreferenced
            # COMDATs: /OPT:REF drops over 200 accepted map anchors and makes
            # .text far too small.  Target constructor-iterator references also
            # prove identical COMDAT folding: four distinct vertex constructors
            # converge on 0x0040B580, so keep REF disabled but enable ICF.
            "/subsystem:windows /machine:X86 /filealign:512 /incremental:no /opt:noref /opt:icf /map /mapinfo:exports /mapinfo:lines",
        )

        writer.variable("msvc_deps_prefix", "Note: including file:")
        writer.rule(
            "cc",
            "$cl /nologo /showIncludes $cl_flags /c $in /Fo$out",
            deps="msvc",
        )
        writer.rule(
            "cc_pbg",
            "$cl /nologo /showIncludes $cl_flags_pbg /c $in /Fo$out",
            deps="msvc",
        )
        writer.rule(
            "cc_detours",
            "$cl /nologo /showIncludes $cl_flags_detours /Fd$out.pdb /Fo$out /c $in",
            deps="msvc",
        )
        writer.rule("genglobals", "python scripts/generate_globals.py $in $out")
        writer.rule("rc", "$rc /fo $out $in")
        writer.rule(
            "link",
            "$link $link_flags /nologo /out:$out $link_libs $in",
        )
        writer.rule("prepareicon", "python scripts/prepare-icon.py $in $out")
        writer.rule(
            "geni18n",
            "python scripts/generate_i18n.py -o $out --shift-jis $in",
        )
        writer.rule(
            "gendetours",
            "python scripts/generate_detours.py --input-def $builddir/th08.def --output $out",
        )
        writer.rule(
            "gendef",
            "python scripts/gendef.py --output $out $in",
        )
        writer.rule(
            "rename_symbols",
            "python scripts/generate_objdiff_objs.py $in",
        )

        use_precompiled_header = '/Yu"th_pch.h"'
        debug_codegen = "/Od " + use_precompiled_header
        small_codegen = "/Os"

        cxx_flags_per_source = {
            "AsciiManager": debug_codegen,
            "AsciiManagerGauge": debug_codegen,
            "AsciiManagerBossMarker": debug_codegen,
            "AsciiManagerScale": debug_codegen,
            "AsciiManagerGuiMode": debug_codegen,
            "Background": debug_codegen,
            "PlayerBomb": debug_codegen,
            "SpellCard": debug_codegen,
            "Ending": debug_codegen,
            "EclManager": debug_codegen,
            "EclGlobals": debug_codegen,
            "EffectManager": debug_codegen,
            "EnemyManager": debug_codegen,
            "BulletManager": debug_codegen,
            "Gui": small_codegen,
            "GameManager": small_codegen + " /Ob1",
            "utils": debug_codegen,
            "Global": debug_codegen,
            "TextHelper": small_codegen,
            "ItemManager": debug_codegen,
            "main": debug_codegen,
            "Midi": debug_codegen,
            "Supervisor": small_codegen + " /Ob1",
            "MusicRoom": small_codegen,
            "Player": debug_codegen,
            "ReplayManager": debug_codegen,
            "ResultScreen": small_codegen + " /Oi-",
            "ScoreDat": debug_codegen,
            "ScreenEffect": debug_codegen,
            "SoundPlayer": debug_codegen,
            "AnmManager": debug_codegen,
            "TitleScreen": small_codegen + " /Oi- /Ob1",
            "zwave": debug_codegen,
        }

        for key, value in cxx_flags_per_source.items():
            writer.rule(
                "cc_" + key,
                "$cl /nologo /showIncludes $cl_flags " + value + " /c $in /Fo$out",
                deps="msvc",
            )

        cxx_sources = [
            "AsciiManager",
            "Background",
            "PlayerBomb",
            "SpellCard",  # card.obj
            "Ending",
            "EclManager",
            "EclGlobals",
            "EffectManager",
            "AsciiManagerBossMarker",
            "EnemyManager",
            "AsciiManagerScale",
            "BulletManager",  # etama.obj
            "Gui",  # front.obj
            "AsciiManagerGuiMode",
            "GameManager",
            "AsciiManagerGauge",
            "utils",
            "Global",
            "TextHelper",  # grpfont.obj
            "ItemManager",
            "main",
            "Midi",
            "Supervisor",  # mother.obj
            "MusicRoom",
            "Player",
            "ReplayManager",
            "ResultScreen",
            "ScoreDat",
            "ScreenEffect",
            "SoundPlayer",
            "AnmManager",  # sprtlib.obj
            "TitleScreen",
            "zwave",
        ]

        # These ECL translation units have a closed natural production-link
        # contract and keep the exact generic /Oi /Gr compile profile used by
        # their reconstruction lane.  Do not route them through the PCH-backed
        # cc_<TU> rules: that changes target codegen.
        production_ecl_sources = [
            "EclOperandsInt",
            "EclOperandsFloat",
            "EnemyManagerUpdate",
            "EclHelpers",
            "EclRun",
            "EnemyTimeline",
            "EclDependencies",
            "EclExIns",
        ]

        # EclManager retains a separate generic-profile comparison probe while
        # its normal PCH-backed production TU remains in cxx_sources.
        re_probe_sources = [
            "EclManager",
        ]

        pbg_sources = [
            "PbgFile",
            "Lzss",
            "PbgArchive",
        ]

        detours_sources = [
            "detours",
            "modules",
            "disasm",
            "image",
            "creatwth",
            "disolx86",
            "disolx64",
            "disolia64",
            "disolarm",
            "disolarm64",
        ]

        # TODO: might make more sense to work the other way around: generate
        # objdiff.json from the ninja.
        with open("objdiff.json") as f:
            objdiff_json = json.load(f)
        objdiff_deps = []
        for obj in objdiff_json.get("objects", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        for obj in objdiff_json.get("units", {}):
            objdiff_deps.append(obj["base_path"].replace("build", "$builddir"))
        # The strict comparison ledger contains probe and reimplementation
        # objects that are not necessarily present in objdiff.json.  The
        # aggregate target must build every configured comparison input so a
        # full replay cannot silently reuse or omit an old object.
        with open("config/match-units.toml", "rb") as f:
            match_units = tomllib.load(f).get("units", [])
        for unit in match_units:
            objdiff_deps.append(str(unit["object"]).replace("build", "$builddir", 1))
        writer.build("objdiff", "phony", [], sorted(set(objdiff_deps)))

        # Precompiled header
        writer.rule(
            "cc_th_pch",
            '$cl /nologo /showIncludes $cl_flags /Yc"th_pch.h"'
            + " /c src/th_pch.cpp /Fo$builddir/th_pch.obj",
            deps="msvc",
        )

        writer.build("$builddir/th_pch.pch", "cc_th_pch", "src/th_pch.cpp")

        for rule in cxx_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_" + rule,
                "src/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for source in production_ecl_sources:
            writer.build(
                "$builddir/" + source + ".obj",
                "cc",
                "src/" + source + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )

        for source in re_probe_sources:
            writer.build(
                "$builddir/probes/" + source + ".obj",
                "cc",
                "src/" + source + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )

        re_probe_objects = ["$builddir/probes/" + source + ".obj" for source in re_probe_sources]
        game_manager_setup_probe = "$builddir/probes/GameManagerSetup.obj"
        writer.build(
            game_manager_setup_probe,
            "cc_GameManager",
            "src/GameManagerSetup.cpp",
            implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
        )
        re_probe_objects.append(game_manager_setup_probe)
        game_manager_score_probe = "$builddir/probes/GameManagerScoreProbe.obj"
        writer.build(
            game_manager_score_probe,
            "cc_GameManager",
            "src/GameManagerScoreProbe.cpp",
            implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
        )
        re_probe_objects.append(game_manager_score_probe)
        stage_menu_probe = "$builddir/probes/StageMenuProbe.obj"
        writer.build(
            stage_menu_probe,
            "cc_AsciiManager",
            "src/StageMenuProbe.cpp",
            implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
        )
        re_probe_objects.append(stage_menu_probe)
        title_replay_probe = "$builddir/probes/TitleReplayMenuProbe.obj"
        writer.build(
            title_replay_probe,
            "cc_TitleScreen",
            "src/TitleReplayMenuProbe.cpp",
            implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
        )
        re_probe_objects.append(title_replay_probe)
        player_option_probe = "$builddir/probes/PlayerOptionProbe.obj"
        writer.build(
            player_option_probe,
            "cc_Player",
            "src/PlayerOptionProbe.cpp",
            implicit=["$builddir/autogenerated/i18n.hpp", "$builddir/th_pch.pch"],
        )
        re_probe_objects.append(player_option_probe)
        writer.build("re-probes", "phony", re_probe_objects)

        for rule in pbg_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_pbg",
                "src/pbg/" + rule + ".cpp",
                implicit=["$builddir/autogenerated/i18n.hpp"],
            )
            writer.build(
                "$builddir/objdiff/reimpl/" + rule + ".obj",
                "rename_symbols",
                "$builddir/" + rule + ".obj",
                implicit=["scripts/generate_objdiff_objs.py"],
            )

        for rule in detours_sources:
            writer.build(
                "$builddir/" + rule + ".obj",
                "cc_detours",
                "3rdparty/Detours/src/" + rule + ".cpp",
            )

        writer.build(
            "$builddir/autogenerated/detouring.cpp",
            "gendetours",
            implicit=[
                "config/implemented.csv",
                "config/mapping.csv",
                "scripts/generate_detours.py",
                "$builddir/th08.def",
            ],
        )
        writer.build(
            "$builddir/dllbuild.obj",
            "cc",
            "src/dllbuild.cpp",
            implicit=[
                "$builddir/autogenerated/detouring.cpp",
                "$builddir/autogenerated/i18n.hpp",
            ],
        )

        writer.build(
            "$builddir/globals.obj",
            "genglobals",
            inputs="config/globals.csv",
            implicit=["scripts/generate_globals.py"],
        )
        writer.build("$builddir/autogenerated/i18n.hpp", "geni18n", "config/i18n.csv")
        writer.build(
            "$builddir/icon.ico",
            "prepareicon",
            "resources/placeholder.ico",
            implicit="scripts/prepare-icon.py",
        )
        writer.build(
            "$builddir/th08.res",
            "rc",
            inputs="resources/th08.rc",
            implicit="$builddir/icon.ico",
        )
        writer.build(
            "$builddir/th08.def",
            "gendef",
            inputs=["$builddir/" + x + ".obj" for x in (cxx_sources + production_ecl_sources + pbg_sources)],
            implicit=["scripts/gendef.py"],
        )
        objfiles = (
            ["$builddir/" + src + ".obj" for src in cxx_sources]
            + ["$builddir/" + src + ".obj" for src in production_ecl_sources]
            + ["$builddir/" + src + ".obj" for src in pbg_sources]
            + ["$builddir/th08.res"]
        )
        if build_type in [BuildType.DIFFBUILD, BuildType.DLLBUILD]:
            objfiles += ["$builddir/globals.obj"]

        # Import descriptors follow the import-library order.  Keep the order
        # observed in the canonical TH08 image: DINPUT8, DSOUND, d3d8, WINMM,
        # KERNEL32, USER32, GDI32, ADVAPI32, ole32.  Static DX libraries remain
        # first and libraries that contribute no descriptor may remain listed.
        th08_link_libs = "dxguid.lib d3dx8.lib dinput8.lib dsound.lib d3d8.lib winmm.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib"
        writer.build(
            "$builddir/th08.exe",
            "link",
            inputs=objfiles,
            implicit=re_probe_objects,
            variables={
                "link_libs": th08_link_libs,
                # The target has no debug data-directory entry.  Compile-time
                # /Zi remains available for object/PDB evidence, but the normal
                # executable must not embed a CodeView path.
                "link_flags": "$th08_link_flags",
            },
        )

        writer.build(
            "$builddir/th08e.dll",
            "link",
            inputs=objfiles + ["$builddir/dllbuild.obj", "$builddir/detours.lib"],
            implicit=["$builddir/th08.def"],
            variables={
                "link_libs": th08_link_libs,
                "link_flags": "/DLL /debug /pdb:$builddir/th08e.pdb /export:DetourFinishHelperProcess,@1,NONAME /def:$builddir/th08.def /export:Direct3DCreate8 /export:malloc /export:calloc /export:realloc /export:??2@YAPAXI@Z /export:free /export:_msize",
            },
        )

        writer.build(
            "$builddir/detours.lib",
            "link",
            inputs=["$builddir/" + s + ".obj" for s in detours_sources],
            variables={"link_flags": "/lib"},
        )

        writer.close()


if __name__ == "__main__":
    configure(BuildType.NORMAL)
