# This script converts an i18n file containing Japanese strings into Shift-JIS
# strings.

import os
import argparse
import csv


def convert_to_sjis(string):
    sjis_str = string.encode("shift_jis")

    converted_str = ""

    i = 0
    while i < len(sjis_str):
        byte = sjis_str[i]

        if byte == ord("\\") and len(sjis_str) > (i + 1):
            second_char = sjis_str[i + 1]

            # handle escape sequences
            if second_char in [ord("r"), ord("n"), ord("\\"), ord('"'), ord("'")]:
                converted_str += "\\" + chr(second_char)
                # skip the \ and escaped character
                i += 2
                continue
        converted_str += "\\x{:02X}".format(byte)
        i += 1

    return converted_str


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("input")
    parser.add_argument("-o", "--output", required=True)
    parser.add_argument("--shift-jis", action="store_true")
    args = parser.parse_args()

    lines = []

    language = "jp"
    if os.getenv("TH_EN") is not None:
        language = "en"

    lines.append("// Autogenerated by " + os.path.basename(__file__) + " Do not edit.")
    lines.append("#pragma once\n")

    with open(args.input, encoding="utf-8") as f:
        reader = csv.DictReader(f, quotechar='"')
        for row in reader:
            identifier = "TH_" + row["identifier"]
            value = ""
            if args.shift_jis:
                value = convert_to_sjis(row[language])
            else:
                value = row[language]

            lines.append("#define " + identifier + ' "' + value + '"')

    with open(args.output, "w") as f:
        f.write("\n".join(lines))


if __name__ == "__main__":
    main()
