#include "Spellcard.hpp"
#include "utils.hpp"

namespace th08
{
// clang-format off
// TODO: stop clang-format from fucking with whitespace formatting

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 42, g_SpellcardNumbersEasy) = {
    // Stage 1
    SPELLCARD_ST1_BOSS_1E,    SPELLCARD_ST1_BOSS_2E,
    // Stage 2
    SPELLCARD_ST2_MBOSS_1E,   SPELLCARD_ST2_BOSS_1E,    SPELLCARD_ST2_BOSS_2E,    SPELLCARD_ST2_BOSS_3E,
    // Stage 3
    SPELLCARD_ST3_MBOSS_1E,   SPELLCARD_ST3_BOSS_2E,    SPELLCARD_ST3_BOSS_3E,    SPELLCARD_ST3_BOSS_4E,
    // Stage 4A
    SPELLCARD_ST4A_MBOSS_1E,  SPELLCARD_ST4A_MBOSS_2E,  SPELLCARD_ST4A_BOSS_1E,   SPELLCARD_ST4A_BOSS_2E,
    SPELLCARD_ST4A_BOSS_3E,
    // Stage 4B
    SPELLCARD_ST4B_MBOSS_1E,  SPELLCARD_ST4B_MBOSS_2E,  SPELLCARD_ST4B_BOSS_1E,   SPELLCARD_ST4B_BOSS_2E,
    SPELLCARD_ST4B_BOSS_3E,
    // Stage 5
    SPELLCARD_ST5_BOSS_1E,    SPELLCARD_ST5_BOSS_2E,    SPELLCARD_ST5_BOSS_3E,    SPELLCARD_ST5_BOSS_4E,
    // Stage 6A
    SPELLCARD_ST6A_MBOSS_1E,  SPELLCARD_ST6A_BOSS_1E,   SPELLCARD_ST6A_BOSS_2E,   SPELLCARD_ST6A_BOSS_3E,
    SPELLCARD_ST6A_BOSS_4E,   SPELLCARD_ST6A_BOSS_5E,   SPELLCARD_ST6A_BOSS_LSE,
    // Stage 6B
    SPELLCARD_ST6B_MBOSS_1E,  SPELLCARD_ST6B_BOSS_1E,   SPELLCARD_ST6B_BOSS_2E,   SPELLCARD_ST6B_BOSS_3E,
    SPELLCARD_ST6B_BOSS_4E,   SPELLCARD_ST6B_BOSS_5E,   SPELLCARD_ST6B_BOSS_LS1E, SPELLCARD_ST6B_BOSS_LS2E,
    SPELLCARD_ST6B_BOSS_LS3E, SPELLCARD_ST6B_BOSS_LS4E, SPELLCARD_ST6B_BOSS_LS5E,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 49, g_SpellcardNumbersNormal) = {
    // Stage 1
    SPELLCARD_ST1_BOSS_1N,    SPELLCARD_ST1_BOSS_2N,    SPELLCARD_ST1_BOSS_LSN,
    // Stage 2
    SPELLCARD_ST2_MBOSS_1N,   SPELLCARD_ST2_BOSS_1N,    SPELLCARD_ST2_BOSS_2N,    SPELLCARD_ST2_BOSS_3N,
    SPELLCARD_ST2_BOSS_LSN,
    // Stage 3
    SPELLCARD_ST3_MBOSS_1N,   SPELLCARD_ST3_BOSS_1N,    SPELLCARD_ST3_BOSS_2N,    SPELLCARD_ST3_BOSS_3N,
    SPELLCARD_ST3_BOSS_4N,    SPELLCARD_ST3_BOSS_LSN,
    // Stage 4A
    SPELLCARD_ST4A_MBOSS_1N,  SPELLCARD_ST4A_MBOSS_2N,  SPELLCARD_ST4A_BOSS_1N,   SPELLCARD_ST4A_BOSS_2N,
    SPELLCARD_ST4A_BOSS_3N,   SPELLCARD_ST4A_BOSS_LSN,
    // Stage 4B
    SPELLCARD_ST4B_MBOSS_1N,  SPELLCARD_ST4B_MBOSS_2N,  SPELLCARD_ST4B_BOSS_1N,   SPELLCARD_ST4B_BOSS_2N,
    SPELLCARD_ST4B_BOSS_3N,   SPELLCARD_ST4B_BOSS_LSN,
    // Stage 5
    SPELLCARD_ST5_BOSS_1N,    SPELLCARD_ST5_BOSS_2N,    SPELLCARD_ST5_BOSS_3N,    SPELLCARD_ST5_BOSS_4N,
    SPELLCARD_ST5_BOSS_LSN,
    // Stage 6A
    SPELLCARD_ST6A_MBOSS_1N,  SPELLCARD_ST6A_BOSS_1N,   SPELLCARD_ST6A_BOSS_2N,   SPELLCARD_ST6A_BOSS_3N,
    SPELLCARD_ST6A_BOSS_4N,   SPELLCARD_ST6A_BOSS_5N,   SPELLCARD_ST6A_BOSS_LSN,
    // Stage 6B
    SPELLCARD_ST6B_MBOSS_1N,  SPELLCARD_ST6B_BOSS_1N,   SPELLCARD_ST6B_BOSS_2N,   SPELLCARD_ST6B_BOSS_3N,
    SPELLCARD_ST6B_BOSS_4N,   SPELLCARD_ST6B_BOSS_5N,   SPELLCARD_ST6B_BOSS_LS1N, SPELLCARD_ST6B_BOSS_LS2N,
    SPELLCARD_ST6B_BOSS_LS3N, SPELLCARD_ST6B_BOSS_LS4N, SPELLCARD_ST6B_BOSS_LS5N,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 50, g_SpellcardNumbersHard) = {
    // Stage 1
    SPELLCARD_ST1_MBOSS_1H,   SPELLCARD_ST1_BOSS_1H,    SPELLCARD_ST1_BOSS_2H,    SPELLCARD_ST1_BOSS_LSH,
    // Stage 2
    SPELLCARD_ST2_MBOSS_1H,   SPELLCARD_ST2_BOSS_1H,    SPELLCARD_ST2_BOSS_2H,    SPELLCARD_ST2_BOSS_3H,
    SPELLCARD_ST2_BOSS_LSH,
    // Stage 3
    SPELLCARD_ST3_MBOSS_1H,   SPELLCARD_ST3_BOSS_1H,    SPELLCARD_ST3_BOSS_2H,    SPELLCARD_ST3_BOSS_3H,
    SPELLCARD_ST3_BOSS_4H,    SPELLCARD_ST3_BOSS_LSH,
    // Stage 4A
    SPELLCARD_ST4A_MBOSS_1H,  SPELLCARD_ST4A_MBOSS_2H,  SPELLCARD_ST4A_BOSS_1H,   SPELLCARD_ST4A_BOSS_2H,
    SPELLCARD_ST4A_BOSS_3H,   SPELLCARD_ST4A_BOSS_LSH,
    // Stage 4B
    SPELLCARD_ST4B_MBOSS_1H,  SPELLCARD_ST4B_MBOSS_2H,  SPELLCARD_ST4B_BOSS_1H,   SPELLCARD_ST4B_BOSS_2H,
    SPELLCARD_ST4B_BOSS_3H,   SPELLCARD_ST4B_BOSS_LSH,
    // Stage 5
    SPELLCARD_ST5_BOSS_1H,    SPELLCARD_ST5_BOSS_2H,    SPELLCARD_ST5_BOSS_3H,    SPELLCARD_ST5_BOSS_4H,
    SPELLCARD_ST5_BOSS_LSH,
    // Stage 6A
    SPELLCARD_ST6A_MBOSS_1H,  SPELLCARD_ST6A_BOSS_1H,   SPELLCARD_ST6A_BOSS_2H,   SPELLCARD_ST6A_BOSS_3H,
    SPELLCARD_ST6A_BOSS_4H,   SPELLCARD_ST6A_BOSS_5H,   SPELLCARD_ST6A_BOSS_LSH,
    // Stage 6B
    SPELLCARD_ST6B_MBOSS_1H,  SPELLCARD_ST6B_BOSS_1H,   SPELLCARD_ST6B_BOSS_2H,   SPELLCARD_ST6B_BOSS_3H,
    SPELLCARD_ST6B_BOSS_4H,   SPELLCARD_ST6B_BOSS_5H,   SPELLCARD_ST6B_BOSS_LS1H, SPELLCARD_ST6B_BOSS_LS2H,
    SPELLCARD_ST6B_BOSS_LS3H, SPELLCARD_ST6B_BOSS_LS4H, SPELLCARD_ST6B_BOSS_LS5H,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 50, g_SpellcardNumbersLunatic) = {
    // Stage 1
    SPELLCARD_ST1_MBOSS_1L,   SPELLCARD_ST1_BOSS_1L,    SPELLCARD_ST1_BOSS_2L,    SPELLCARD_ST1_BOSS_LSL,
    // Stage 2
    SPELLCARD_ST2_MBOSS_1L,   SPELLCARD_ST2_BOSS_1L,    SPELLCARD_ST2_BOSS_2L,    SPELLCARD_ST2_BOSS_3L,
    SPELLCARD_ST2_BOSS_LSL,
    // Stage 3
    SPELLCARD_ST3_MBOSS_1L,   SPELLCARD_ST3_BOSS_1L,    SPELLCARD_ST3_BOSS_2L,    SPELLCARD_ST3_BOSS_3L,
    SPELLCARD_ST3_BOSS_4L,    SPELLCARD_ST3_BOSS_LSL,
    // Stage 4A
    SPELLCARD_ST4A_MBOSS_1L,  SPELLCARD_ST4A_MBOSS_2L,  SPELLCARD_ST4A_BOSS_1L,   SPELLCARD_ST4A_BOSS_2L,
    SPELLCARD_ST4A_BOSS_3L,   SPELLCARD_ST4A_BOSS_LSL,
    // Stage 4B
    SPELLCARD_ST4B_MBOSS_1L,  SPELLCARD_ST4B_MBOSS_2L,  SPELLCARD_ST4B_BOSS_1L,   SPELLCARD_ST4B_BOSS_2L,
    SPELLCARD_ST4B_BOSS_3L,   SPELLCARD_ST4B_BOSS_LSL,
    // Stage 5
    SPELLCARD_ST5_BOSS_1L,    SPELLCARD_ST5_BOSS_2L,    SPELLCARD_ST5_BOSS_3L,    SPELLCARD_ST5_BOSS_4L,
    SPELLCARD_ST5_BOSS_LSL,
    // Stage 6A
    SPELLCARD_ST6A_MBOSS_1L,  SPELLCARD_ST6A_BOSS_1L,   SPELLCARD_ST6A_BOSS_2L,   SPELLCARD_ST6A_BOSS_3L,
    SPELLCARD_ST6A_BOSS_4L,   SPELLCARD_ST6A_BOSS_5L,   SPELLCARD_ST6A_BOSS_LSL,
    // Stage 6B
    SPELLCARD_ST6B_MBOSS_1L,  SPELLCARD_ST6B_BOSS_1L,   SPELLCARD_ST6B_BOSS_2L,   SPELLCARD_ST6B_BOSS_3L,
    SPELLCARD_ST6B_BOSS_4L,   SPELLCARD_ST6B_BOSS_5L,   SPELLCARD_ST6B_BOSS_LS1L, SPELLCARD_ST6B_BOSS_LS2L,
    SPELLCARD_ST6B_BOSS_LS3L, SPELLCARD_ST6B_BOSS_LS4L, SPELLCARD_ST6B_BOSS_LS5L,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 14, g_SpellcardNumbersExtra) = {
    SPELLCARD_EX_MBOSS_1, SPELLCARD_EX_MBOSS_2, SPELLCARD_EX_MBOSS_3,
    SPELLCARD_EX_BOSS_1,  SPELLCARD_EX_BOSS_2,  SPELLCARD_EX_BOSS_3,  SPELLCARD_EX_BOSS_4,
    SPELLCARD_EX_BOSS_5,  SPELLCARD_EX_BOSS_6,  SPELLCARD_EX_BOSS_7,  SPELLCARD_EX_BOSS_8,
    SPELLCARD_EX_BOSS_9,  SPELLCARD_EX_BOSS_10, SPELLCARD_EX_BOSS_LS,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, SPELLCARD_COUNT_SPELLCARDS, g_SpellcardNumbersAllDifficulties) = {
    // Stage 1
                                                        SPELLCARD_ST1_MBOSS_1H,   SPELLCARD_ST1_MBOSS_1L,
    SPELLCARD_ST1_BOSS_1E,    SPELLCARD_ST1_BOSS_1N,    SPELLCARD_ST1_BOSS_1H,    SPELLCARD_ST1_BOSS_1L,
    SPELLCARD_ST1_BOSS_2E,    SPELLCARD_ST1_BOSS_2N,    SPELLCARD_ST1_BOSS_2H,    SPELLCARD_ST1_BOSS_2L,
                              SPELLCARD_ST1_BOSS_LSN,   SPELLCARD_ST1_BOSS_LSH,   SPELLCARD_ST1_BOSS_LSL,
    // Stage 2
    SPELLCARD_ST2_MBOSS_1E,   SPELLCARD_ST2_MBOSS_1N,   SPELLCARD_ST2_MBOSS_1H,   SPELLCARD_ST2_MBOSS_1L,
    SPELLCARD_ST2_BOSS_1E,    SPELLCARD_ST2_BOSS_1N,    SPELLCARD_ST2_BOSS_1H,    SPELLCARD_ST2_BOSS_1L,
    SPELLCARD_ST2_BOSS_2E,    SPELLCARD_ST2_BOSS_2N,    SPELLCARD_ST2_BOSS_2H,    SPELLCARD_ST2_BOSS_2L,
    SPELLCARD_ST2_BOSS_3E,    SPELLCARD_ST2_BOSS_3N,    SPELLCARD_ST2_BOSS_3H,    SPELLCARD_ST2_BOSS_3L,
                              SPELLCARD_ST2_BOSS_LSN,   SPELLCARD_ST2_BOSS_LSH,   SPELLCARD_ST2_BOSS_LSL,
    // Stage 3
    SPELLCARD_ST3_MBOSS_1E,   SPELLCARD_ST3_MBOSS_1N,   SPELLCARD_ST3_MBOSS_1H,   SPELLCARD_ST3_MBOSS_1L,
                              SPELLCARD_ST3_BOSS_1N,    SPELLCARD_ST3_BOSS_1H,    SPELLCARD_ST3_BOSS_1L,
    SPELLCARD_ST3_BOSS_2E,    SPELLCARD_ST3_BOSS_2N,    SPELLCARD_ST3_BOSS_2H,    SPELLCARD_ST3_BOSS_2L,
    SPELLCARD_ST3_BOSS_3E,    SPELLCARD_ST3_BOSS_3N,    SPELLCARD_ST3_BOSS_3H,    SPELLCARD_ST3_BOSS_3L,
    SPELLCARD_ST3_BOSS_4E,    SPELLCARD_ST3_BOSS_4N,    SPELLCARD_ST3_BOSS_4H,    SPELLCARD_ST3_BOSS_4L,
                              SPELLCARD_ST3_BOSS_LSN,   SPELLCARD_ST3_BOSS_LSH,   SPELLCARD_ST3_BOSS_LSL,
    // Stage 4A
    SPELLCARD_ST4A_MBOSS_1E,  SPELLCARD_ST4A_MBOSS_1N,  SPELLCARD_ST4A_MBOSS_1H,  SPELLCARD_ST4A_MBOSS_1L,
    SPELLCARD_ST4A_MBOSS_2E,  SPELLCARD_ST4A_MBOSS_2N,  SPELLCARD_ST4A_MBOSS_2H,  SPELLCARD_ST4A_MBOSS_2L,
    SPELLCARD_ST4A_BOSS_1E,   SPELLCARD_ST4A_BOSS_1N,   SPELLCARD_ST4A_BOSS_1H,   SPELLCARD_ST4A_BOSS_1L,
    SPELLCARD_ST4A_BOSS_2E,   SPELLCARD_ST4A_BOSS_2N,   SPELLCARD_ST4A_BOSS_2H,   SPELLCARD_ST4A_BOSS_2L,
    SPELLCARD_ST4A_BOSS_3E,   SPELLCARD_ST4A_BOSS_3N,   SPELLCARD_ST4A_BOSS_3H,   SPELLCARD_ST4A_BOSS_3L,
                              SPELLCARD_ST4A_BOSS_LSN,  SPELLCARD_ST4A_BOSS_LSH,  SPELLCARD_ST4A_BOSS_LSL,
    // Stage 4B
    SPELLCARD_ST4B_MBOSS_1E,  SPELLCARD_ST4B_MBOSS_1N,  SPELLCARD_ST4B_MBOSS_1H,  SPELLCARD_ST4B_MBOSS_1L,
    SPELLCARD_ST4B_MBOSS_2E,  SPELLCARD_ST4B_MBOSS_2N,  SPELLCARD_ST4B_MBOSS_2H,  SPELLCARD_ST4B_MBOSS_2L,
    SPELLCARD_ST4B_BOSS_1E,   SPELLCARD_ST4B_BOSS_1N,   SPELLCARD_ST4B_BOSS_1H,   SPELLCARD_ST4B_BOSS_1L,
    SPELLCARD_ST4B_BOSS_2E,   SPELLCARD_ST4B_BOSS_2N,   SPELLCARD_ST4B_BOSS_2H,   SPELLCARD_ST4B_BOSS_2L,
    SPELLCARD_ST4B_BOSS_3E,   SPELLCARD_ST4B_BOSS_3N,   SPELLCARD_ST4B_BOSS_3H,   SPELLCARD_ST4B_BOSS_3L,
                              SPELLCARD_ST4B_BOSS_LSN,  SPELLCARD_ST4B_BOSS_LSH,  SPELLCARD_ST4B_BOSS_LSL,
    // Stage 5
    SPELLCARD_ST5_BOSS_1E,    SPELLCARD_ST5_BOSS_1N,    SPELLCARD_ST5_BOSS_1H,    SPELLCARD_ST5_BOSS_1L,
    SPELLCARD_ST5_BOSS_2E,    SPELLCARD_ST5_BOSS_2N,    SPELLCARD_ST5_BOSS_2H,    SPELLCARD_ST5_BOSS_2L,
    SPELLCARD_ST5_BOSS_3E,    SPELLCARD_ST5_BOSS_3N,    SPELLCARD_ST5_BOSS_3H,    SPELLCARD_ST5_BOSS_3L,
    SPELLCARD_ST5_BOSS_4E,    SPELLCARD_ST5_BOSS_4N,    SPELLCARD_ST5_BOSS_4H,    SPELLCARD_ST5_BOSS_4L,
                              SPELLCARD_ST5_BOSS_LSN,   SPELLCARD_ST5_BOSS_LSH,   SPELLCARD_ST5_BOSS_LSL,
    // Stage 6A
    SPELLCARD_ST6A_MBOSS_1E,  SPELLCARD_ST6A_MBOSS_1N,  SPELLCARD_ST6A_MBOSS_1H,  SPELLCARD_ST6A_MBOSS_1L,
    SPELLCARD_ST6A_BOSS_1E,   SPELLCARD_ST6A_BOSS_1N,   SPELLCARD_ST6A_BOSS_1H,   SPELLCARD_ST6A_BOSS_1L,
    SPELLCARD_ST6A_BOSS_2E,   SPELLCARD_ST6A_BOSS_2N,   SPELLCARD_ST6A_BOSS_2H,   SPELLCARD_ST6A_BOSS_2L,
    SPELLCARD_ST6A_BOSS_3E,   SPELLCARD_ST6A_BOSS_3N,   SPELLCARD_ST6A_BOSS_3H,   SPELLCARD_ST6A_BOSS_3L,
    SPELLCARD_ST6A_BOSS_4E,   SPELLCARD_ST6A_BOSS_4N,   SPELLCARD_ST6A_BOSS_4H,   SPELLCARD_ST6A_BOSS_4L,
    SPELLCARD_ST6A_BOSS_5E,   SPELLCARD_ST6A_BOSS_5N,   SPELLCARD_ST6A_BOSS_5H,   SPELLCARD_ST6A_BOSS_5L,
    SPELLCARD_ST6A_BOSS_LSE,  SPELLCARD_ST6A_BOSS_LSN,  SPELLCARD_ST6A_BOSS_LSH,  SPELLCARD_ST6A_BOSS_LSL,
    // Stage 6B
    SPELLCARD_ST6B_MBOSS_1E,  SPELLCARD_ST6B_MBOSS_1N,  SPELLCARD_ST6B_MBOSS_1H,  SPELLCARD_ST6B_MBOSS_1L,
    SPELLCARD_ST6B_BOSS_1E,   SPELLCARD_ST6B_BOSS_1N,   SPELLCARD_ST6B_BOSS_1H,   SPELLCARD_ST6B_BOSS_1L,
    SPELLCARD_ST6B_BOSS_2E,   SPELLCARD_ST6B_BOSS_2N,   SPELLCARD_ST6B_BOSS_2H,   SPELLCARD_ST6B_BOSS_2L,
    SPELLCARD_ST6B_BOSS_3E,   SPELLCARD_ST6B_BOSS_3N,   SPELLCARD_ST6B_BOSS_3H,   SPELLCARD_ST6B_BOSS_3L,
    SPELLCARD_ST6B_BOSS_4E,   SPELLCARD_ST6B_BOSS_4N,   SPELLCARD_ST6B_BOSS_4H,   SPELLCARD_ST6B_BOSS_4L,
    SPELLCARD_ST6B_BOSS_5E,   SPELLCARD_ST6B_BOSS_5N,   SPELLCARD_ST6B_BOSS_5H,   SPELLCARD_ST6B_BOSS_5L,
    SPELLCARD_ST6B_BOSS_LS1E, SPELLCARD_ST6B_BOSS_LS1N, SPELLCARD_ST6B_BOSS_LS1H, SPELLCARD_ST6B_BOSS_LS1L,
    SPELLCARD_ST6B_BOSS_LS2E, SPELLCARD_ST6B_BOSS_LS2N, SPELLCARD_ST6B_BOSS_LS2H, SPELLCARD_ST6B_BOSS_LS2L,
    SPELLCARD_ST6B_BOSS_LS3E, SPELLCARD_ST6B_BOSS_LS3N, SPELLCARD_ST6B_BOSS_LS3H, SPELLCARD_ST6B_BOSS_LS3L,
    SPELLCARD_ST6B_BOSS_LS4E, SPELLCARD_ST6B_BOSS_LS4N, SPELLCARD_ST6B_BOSS_LS4H, SPELLCARD_ST6B_BOSS_LS4L,
    SPELLCARD_ST6B_BOSS_LS5E, SPELLCARD_ST6B_BOSS_LS5N, SPELLCARD_ST6B_BOSS_LS5H, SPELLCARD_ST6B_BOSS_LS5L,
    // Extra Stage
    SPELLCARD_EX_MBOSS_1,     SPELLCARD_EX_MBOSS_2,     SPELLCARD_EX_MBOSS_3,
    SPELLCARD_EX_BOSS_1,      SPELLCARD_EX_BOSS_2,      SPELLCARD_EX_BOSS_3,      SPELLCARD_EX_BOSS_4,
    SPELLCARD_EX_BOSS_5,      SPELLCARD_EX_BOSS_6,      SPELLCARD_EX_BOSS_7,      SPELLCARD_EX_BOSS_8,
    SPELLCARD_EX_BOSS_9,      SPELLCARD_EX_BOSS_10,     SPELLCARD_EX_BOSS_LS,
    // Last Word
    SPELLCARD_LW_WRIGGLE,     SPELLCARD_LW_MYSTIA,      SPELLCARD_LW_KEINE,       SPELLCARD_LW_REISEN,
    SPELLCARD_LW_EIRIN,       SPELLCARD_LW_KAGUYA,      SPELLCARD_LW_MOKOU,       SPELLCARD_LW_TEWI,
    SPELLCARD_LW_KEINEEX,     SPELLCARD_LW_REIMU,       SPELLCARD_LW_MARISA,      SPELLCARD_LW_SAKUYA,
    SPELLCARD_LW_YOUMU,       SPELLCARD_LW_ALICE,       SPELLCARD_LW_REMILIA,     SPELLCARD_LW_YUYUKO,
    SPELLCARD_LW_YUKARI,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32 *, 6, g_SpellcardNumbersPerDifficulty) = {
    g_SpellcardNumbersEasy,    g_SpellcardNumbersNormal, g_SpellcardNumbersHard,
    g_SpellcardNumbersLunatic, g_SpellcardNumbersExtra,  g_SpellcardNumbersAllDifficulties};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 6, g_SpellcardCountsPerDifficulty) = {
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersEasy),  ARRAY_SIZE_SIGNED(g_SpellcardNumbersNormal),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersHard),  ARRAY_SIZE_SIGNED(g_SpellcardNumbersLunatic),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersExtra), ARRAY_SIZE_SIGNED(g_SpellcardNumbersAllDifficulties)};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 13, g_SpellcardNumbersStage1) = {
                                                   SPELLCARD_ST1_MBOSS_1H, SPELLCARD_ST1_MBOSS_1L,
    SPELLCARD_ST1_BOSS_1E, SPELLCARD_ST1_BOSS_1N,  SPELLCARD_ST1_BOSS_1H,  SPELLCARD_ST1_BOSS_1L,
    SPELLCARD_ST1_BOSS_2E, SPELLCARD_ST1_BOSS_2N,  SPELLCARD_ST1_BOSS_2H,  SPELLCARD_ST1_BOSS_2L,
                           SPELLCARD_ST1_BOSS_LSN, SPELLCARD_ST1_BOSS_LSH, SPELLCARD_ST1_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 19, g_SpellcardNumbersStage2) = {
    SPELLCARD_ST2_MBOSS_1E, SPELLCARD_ST2_MBOSS_1N, SPELLCARD_ST2_MBOSS_1H, SPELLCARD_ST2_MBOSS_1L,
    SPELLCARD_ST2_BOSS_1E,  SPELLCARD_ST2_BOSS_1N,  SPELLCARD_ST2_BOSS_1H,  SPELLCARD_ST2_BOSS_1L,
    SPELLCARD_ST2_BOSS_2E,  SPELLCARD_ST2_BOSS_2N,  SPELLCARD_ST2_BOSS_2H,  SPELLCARD_ST2_BOSS_2L,
    SPELLCARD_ST2_BOSS_3E,  SPELLCARD_ST2_BOSS_3N,  SPELLCARD_ST2_BOSS_3H,  SPELLCARD_ST2_BOSS_3L,
                            SPELLCARD_ST2_BOSS_LSN, SPELLCARD_ST2_BOSS_LSH, SPELLCARD_ST2_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 22, g_SpellcardNumbersStage3) = {
    SPELLCARD_ST3_MBOSS_1E, SPELLCARD_ST3_MBOSS_1N, SPELLCARD_ST3_MBOSS_1H, SPELLCARD_ST3_MBOSS_1L,
                            SPELLCARD_ST3_BOSS_1N,  SPELLCARD_ST3_BOSS_1H,  SPELLCARD_ST3_BOSS_1L,
    SPELLCARD_ST3_BOSS_2E,  SPELLCARD_ST3_BOSS_2N,  SPELLCARD_ST3_BOSS_2H,  SPELLCARD_ST3_BOSS_2L,
    SPELLCARD_ST3_BOSS_3E,  SPELLCARD_ST3_BOSS_3N,  SPELLCARD_ST3_BOSS_3H,  SPELLCARD_ST3_BOSS_3L,
    SPELLCARD_ST3_BOSS_4E,  SPELLCARD_ST3_BOSS_4N,  SPELLCARD_ST3_BOSS_4H,  SPELLCARD_ST3_BOSS_4L,
                            SPELLCARD_ST3_BOSS_LSN, SPELLCARD_ST3_BOSS_LSH, SPELLCARD_ST3_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 23, g_SpellcardNumbersStage4A) = {
    SPELLCARD_ST4A_MBOSS_1E, SPELLCARD_ST4A_MBOSS_1N, SPELLCARD_ST4A_MBOSS_1H, SPELLCARD_ST4A_MBOSS_1L,
    SPELLCARD_ST4A_MBOSS_2E, SPELLCARD_ST4A_MBOSS_2N, SPELLCARD_ST4A_MBOSS_2H, SPELLCARD_ST4A_MBOSS_2L,
    SPELLCARD_ST4A_BOSS_1E,  SPELLCARD_ST4A_BOSS_1N,  SPELLCARD_ST4A_BOSS_1H,  SPELLCARD_ST4A_BOSS_1L,
    SPELLCARD_ST4A_BOSS_2E,  SPELLCARD_ST4A_BOSS_2N,  SPELLCARD_ST4A_BOSS_2H,  SPELLCARD_ST4A_BOSS_2L,
    SPELLCARD_ST4A_BOSS_3E,  SPELLCARD_ST4A_BOSS_3N,  SPELLCARD_ST4A_BOSS_3H,  SPELLCARD_ST4A_BOSS_3L,
                             SPELLCARD_ST4A_BOSS_LSN, SPELLCARD_ST4A_BOSS_LSH, SPELLCARD_ST4A_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 23, g_SpellcardNumbersStage4B) = {
    SPELLCARD_ST4B_MBOSS_1E, SPELLCARD_ST4B_MBOSS_1N, SPELLCARD_ST4B_MBOSS_1H, SPELLCARD_ST4B_MBOSS_1L,
    SPELLCARD_ST4B_MBOSS_2E, SPELLCARD_ST4B_MBOSS_2N, SPELLCARD_ST4B_MBOSS_2H, SPELLCARD_ST4B_MBOSS_2L,
    SPELLCARD_ST4B_BOSS_1E,  SPELLCARD_ST4B_BOSS_1N,  SPELLCARD_ST4B_BOSS_1H,  SPELLCARD_ST4B_BOSS_1L,
    SPELLCARD_ST4B_BOSS_2E,  SPELLCARD_ST4B_BOSS_2N,  SPELLCARD_ST4B_BOSS_2H,  SPELLCARD_ST4B_BOSS_2L,
    SPELLCARD_ST4B_BOSS_3E,  SPELLCARD_ST4B_BOSS_3N,  SPELLCARD_ST4B_BOSS_3H,  SPELLCARD_ST4B_BOSS_3L,
                             SPELLCARD_ST4B_BOSS_LSN, SPELLCARD_ST4B_BOSS_LSH, SPELLCARD_ST4B_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 19, g_SpellcardNumbersStage5) = {
    SPELLCARD_ST5_BOSS_1E, SPELLCARD_ST5_BOSS_1N,  SPELLCARD_ST5_BOSS_1H,  SPELLCARD_ST5_BOSS_1L,
    SPELLCARD_ST5_BOSS_2E, SPELLCARD_ST5_BOSS_2N,  SPELLCARD_ST5_BOSS_2H,  SPELLCARD_ST5_BOSS_2L,
    SPELLCARD_ST5_BOSS_3E, SPELLCARD_ST5_BOSS_3N,  SPELLCARD_ST5_BOSS_3H,  SPELLCARD_ST5_BOSS_3L,
    SPELLCARD_ST5_BOSS_4E, SPELLCARD_ST5_BOSS_4N,  SPELLCARD_ST5_BOSS_4H,  SPELLCARD_ST5_BOSS_4L,
                           SPELLCARD_ST5_BOSS_LSN, SPELLCARD_ST5_BOSS_LSH, SPELLCARD_ST5_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 28, g_SpellcardNumbersStage6A) = {
    SPELLCARD_ST6A_MBOSS_1E, SPELLCARD_ST6A_MBOSS_1N, SPELLCARD_ST6A_MBOSS_1H, SPELLCARD_ST6A_MBOSS_1L,
    SPELLCARD_ST6A_BOSS_1E,  SPELLCARD_ST6A_BOSS_1N,  SPELLCARD_ST6A_BOSS_1H,  SPELLCARD_ST6A_BOSS_1L,
    SPELLCARD_ST6A_BOSS_2E,  SPELLCARD_ST6A_BOSS_2N,  SPELLCARD_ST6A_BOSS_2H,  SPELLCARD_ST6A_BOSS_2L,
    SPELLCARD_ST6A_BOSS_3E,  SPELLCARD_ST6A_BOSS_3N,  SPELLCARD_ST6A_BOSS_3H,  SPELLCARD_ST6A_BOSS_3L,
    SPELLCARD_ST6A_BOSS_4E,  SPELLCARD_ST6A_BOSS_4N,  SPELLCARD_ST6A_BOSS_4H,  SPELLCARD_ST6A_BOSS_4L,
    SPELLCARD_ST6A_BOSS_5E,  SPELLCARD_ST6A_BOSS_5N,  SPELLCARD_ST6A_BOSS_5H,  SPELLCARD_ST6A_BOSS_5L,
    SPELLCARD_ST6A_BOSS_LSE, SPELLCARD_ST6A_BOSS_LSN, SPELLCARD_ST6A_BOSS_LSH, SPELLCARD_ST6A_BOSS_LSL,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 44, g_SpellcardNumbersStage6B) = {
    SPELLCARD_ST6B_MBOSS_1E,  SPELLCARD_ST6B_MBOSS_1N,  SPELLCARD_ST6B_MBOSS_1H,  SPELLCARD_ST6B_MBOSS_1L,
    SPELLCARD_ST6B_BOSS_1E,   SPELLCARD_ST6B_BOSS_1N,   SPELLCARD_ST6B_BOSS_1H,   SPELLCARD_ST6B_BOSS_1L,
    SPELLCARD_ST6B_BOSS_2E,   SPELLCARD_ST6B_BOSS_2N,   SPELLCARD_ST6B_BOSS_2H,   SPELLCARD_ST6B_BOSS_2L,
    SPELLCARD_ST6B_BOSS_3E,   SPELLCARD_ST6B_BOSS_3N,   SPELLCARD_ST6B_BOSS_3H,   SPELLCARD_ST6B_BOSS_3L,
    SPELLCARD_ST6B_BOSS_4E,   SPELLCARD_ST6B_BOSS_4N,   SPELLCARD_ST6B_BOSS_4H,   SPELLCARD_ST6B_BOSS_4L,
    SPELLCARD_ST6B_BOSS_5E,   SPELLCARD_ST6B_BOSS_5N,   SPELLCARD_ST6B_BOSS_5H,   SPELLCARD_ST6B_BOSS_5L,
    SPELLCARD_ST6B_BOSS_LS1E, SPELLCARD_ST6B_BOSS_LS1N, SPELLCARD_ST6B_BOSS_LS1H, SPELLCARD_ST6B_BOSS_LS1L,
    SPELLCARD_ST6B_BOSS_LS2E, SPELLCARD_ST6B_BOSS_LS2N, SPELLCARD_ST6B_BOSS_LS2H, SPELLCARD_ST6B_BOSS_LS2L,
    SPELLCARD_ST6B_BOSS_LS3E, SPELLCARD_ST6B_BOSS_LS3N, SPELLCARD_ST6B_BOSS_LS3H, SPELLCARD_ST6B_BOSS_LS3L,
    SPELLCARD_ST6B_BOSS_LS4E, SPELLCARD_ST6B_BOSS_LS4N, SPELLCARD_ST6B_BOSS_LS4H, SPELLCARD_ST6B_BOSS_LS4L,
    SPELLCARD_ST6B_BOSS_LS5E, SPELLCARD_ST6B_BOSS_LS5N, SPELLCARD_ST6B_BOSS_LS5H, SPELLCARD_ST6B_BOSS_LS5L,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 14, g_SpellcardNumbersStageExtra) = {
    SPELLCARD_EX_MBOSS_1, SPELLCARD_EX_MBOSS_2, SPELLCARD_EX_MBOSS_3,
    SPELLCARD_EX_BOSS_1,  SPELLCARD_EX_BOSS_2,  SPELLCARD_EX_BOSS_3,  SPELLCARD_EX_BOSS_4,
    SPELLCARD_EX_BOSS_5,  SPELLCARD_EX_BOSS_6,  SPELLCARD_EX_BOSS_7,  SPELLCARD_EX_BOSS_8,
    SPELLCARD_EX_BOSS_9,  SPELLCARD_EX_BOSS_10, SPELLCARD_EX_BOSS_LS,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 17, g_SpellcardNumbersLastWord) = {
    SPELLCARD_LW_WRIGGLE,
    SPELLCARD_LW_MYSTIA,
    SPELLCARD_LW_KEINE,
    SPELLCARD_LW_REISEN,
    SPELLCARD_LW_EIRIN,
    SPELLCARD_LW_KAGUYA,
    SPELLCARD_LW_MOKOU,
    SPELLCARD_LW_TEWI,
    SPELLCARD_LW_KEINEEX,
    SPELLCARD_LW_REIMU,
    SPELLCARD_LW_MARISA,
    SPELLCARD_LW_SAKUYA,
    SPELLCARD_LW_YOUMU,
    SPELLCARD_LW_ALICE,
    SPELLCARD_LW_REMILIA,
    SPELLCARD_LW_YUYUKO,
    SPELLCARD_LW_YUKARI,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 43, g_LastSpellNumbers) = {
    // Wriggle Nightbug
    SPELLCARD_ST1_BOSS_LSN,   SPELLCARD_ST1_BOSS_LSH,   SPELLCARD_ST1_BOSS_LSL,
    // Mystia Lorelei
    SPELLCARD_ST2_BOSS_LSN,   SPELLCARD_ST2_BOSS_LSH,   SPELLCARD_ST2_BOSS_LSL,
    // Keine Kamishirasawa
    SPELLCARD_ST3_BOSS_LSN,   SPELLCARD_ST3_BOSS_LSH,   SPELLCARD_ST3_BOSS_LSL,
    // Reimu Hakurei
    SPELLCARD_ST4A_BOSS_LSN,  SPELLCARD_ST4A_BOSS_LSH,  SPELLCARD_ST4A_BOSS_LSL,
    // Marisa Kirisame
    SPELLCARD_ST4B_BOSS_LSN,  SPELLCARD_ST4B_BOSS_LSH,  SPELLCARD_ST4B_BOSS_LSL,
    // Reisen U. Inaba
    SPELLCARD_ST5_BOSS_LSN,   SPELLCARD_ST5_BOSS_LSH,   SPELLCARD_ST5_BOSS_LSL,
    // Eirin Yagokoro
    SPELLCARD_ST6A_BOSS_LSE,  SPELLCARD_ST6A_BOSS_LSN,  SPELLCARD_ST6A_BOSS_LSH,  SPELLCARD_ST6A_BOSS_LSL,

    // Kaguya Houraisan, Spell 1
    SPELLCARD_ST6B_BOSS_LS1E, SPELLCARD_ST6B_BOSS_LS1N, SPELLCARD_ST6B_BOSS_LS1H, SPELLCARD_ST6B_BOSS_LS1L,
    // Kaguya Houraisan, Spell 2
    SPELLCARD_ST6B_BOSS_LS2E, SPELLCARD_ST6B_BOSS_LS2N, SPELLCARD_ST6B_BOSS_LS2H, SPELLCARD_ST6B_BOSS_LS2L,
    // Kaguya Houraisan, Spell 3
    SPELLCARD_ST6B_BOSS_LS3E, SPELLCARD_ST6B_BOSS_LS3N, SPELLCARD_ST6B_BOSS_LS3H, SPELLCARD_ST6B_BOSS_LS3L,
    // Kaguya Houraisan, Spell 4
    SPELLCARD_ST6B_BOSS_LS4E, SPELLCARD_ST6B_BOSS_LS4N, SPELLCARD_ST6B_BOSS_LS4H, SPELLCARD_ST6B_BOSS_LS4L,
    // Kaguya Houraisan, Spell 5
    SPELLCARD_ST6B_BOSS_LS5E, SPELLCARD_ST6B_BOSS_LS5N, SPELLCARD_ST6B_BOSS_LS5H, SPELLCARD_ST6B_BOSS_LS5L,

    // Fujiwara no Mokou
    SPELLCARD_EX_BOSS_LS,
};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32 *, 10, g_SpellcardNumbersPerStage) = {
    g_SpellcardNumbersStage1,     g_SpellcardNumbersStage2,  g_SpellcardNumbersStage3,  g_SpellcardNumbersStage4A,
    g_SpellcardNumbersStage4B,    g_SpellcardNumbersStage5,  g_SpellcardNumbersStage6A, g_SpellcardNumbersStage6B,
    g_SpellcardNumbersStageExtra, g_SpellcardNumbersLastWord};

DIFFABLE_STATIC_ARRAY_ASSIGN(i32, 10, g_SpellcardCountPerStage) = {
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage1),  ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage2),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage3),  ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage4A),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage4B), ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage5),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage6A), ARRAY_SIZE_SIGNED(g_SpellcardNumbersStage6B),
    ARRAY_SIZE_SIGNED(g_SpellcardNumbersExtra),   ARRAY_SIZE_SIGNED(g_SpellcardNumbersLastWord)};

// clang-format on
// TODO: stop clang-format from fucking with whitespace formatting

// STUB: th08 0x4144d0
i32 Spellcard::GetDifficultyFromSpellCard(i32 spellCardNumber)
{
    return 0;
}

} /* namespace th08 */